

name: 'dbt_checkpoint3_dw'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_checkpoint3_dw'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_checkpoint3_dw:
    staging:
      +schema: "{{ var('DATABRICKS_SCHEMA_STAGING') }}"
      +materialized: view

    marts:
      +schema: "{{ var('DATABRICKS_SCHEMA_MARTS') }}"
      +materialized: table
