dbt_checkpoint3_dw:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ var('DATABRICKS_CATALOG') }}"
      schema: "db"
      host: "{{ var('DATABRICKS_HOST') }}"
      http_path: "{{ var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ var('DATABRICKS_TOKEN') }}"
      threads: 4
