dbt_checkpoint3_dw:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: ted_dev                    # ou o que você estiver usando
      schema: dev_alexandre_filho
      host: https://dbc-e7cea7f3-e424.cloud.databricks.com
      http_path: /sql/1.0/warehouses/e9fc9bad6a55f558
      token: dapi44f08d8a4fc3eeb82332788aa031b90f
      threads: 4
