version: 2

models:
  - name: fact_sales_order
    description: "Fato de vendas, baseado na staging stg_sales_order_details"
    tests:
      - not_null:
          column_name: order_id
    Columns:
      - name: order_id
        description: "ID do pedido de venda"
      - name: order_detail_id
        description: "ID do detalhe do pedido de venda"
      - name: product_id
        description: "ID do produto"
      - name: customer_id
        description: "ID do cliente"
      - name: salesperson_id
        description: "ID do vendedor"
      - name: territory_id
        description: "ID do território de vendas"
      - name: order_date
        description: "Data do pedido de venda"
      - name: due_date
        description: "Data de vencimento do pedido de venda"
      - name: ship_date
        description: "Data de envio do pedido de venda"
      - name: ship_method_id
        description: "ID do método de envio"
      - name: currency_rate_id
        description: "ID da taxa de câmbio"
      - name: order_quantity
        description: "Quantidade do pedido de venda"
      - name: unit_price
        description: "Preço unitário do produto no pedido de venda"
      - name: unit_price_discount
        description: "Desconto aplicado ao preço unitário do produto no pedido de venda"
      - name: line_total
        description: "Total da linha do pedido de venda (quantidade * preço unitário - desconto)"
      - name: gross_revenue
        description: "Receita bruta do pedido de venda (total da linha * taxa de câmbio)" 
      - name: is_online_order
        description: "Indica se o pedido de venda foi feito online (booleano)"
      - name: ingestion_timestamp
        description: "Timestamp de ingestão do dado no sistema"

  - name: fact_sales_summary_monthly
    description: "Fato de resumo de vendas mensais, baseado na staging stg_sales"
    tests:
      - not_null:
          column_name: year_month
      - unique:
          column_name: (year_month, territory_id, is_online_order)
    Columns:
      - name: year_month
        description: "Ano e mês do resumo de vendas (formato YYYY-MM)"
      - name: territory_id
        description: "ID do território de vendas"
      - name: territory_name
        description: "Nome do território de vendas"
      - name: is_online_order
        description: "Indica se o resumo de vendas é para pedidos online (booleano)"
      - name: total_orders
        description: "Total de pedidos de venda no mês"
      - name: total_items_sold
        description: "Total de itens vendidos no mês"
      - name: revenue
        description: "Receita total do mês (soma de gross_revenue dos pedidos)"
      - name: freight_total
        description: "Total de frete no mês (soma de freight_charge dos pedidos)"
      - name: tax_total
        description: "Total de impostos no mês (soma de tax_charge dos pedidos)"
      - name: average_order_value
        description: "Valor médio dos pedidos no mês (receita total / total de pedidos)"
  
  - name: dim_date
    description: "Dimensão de datas usada para análises temporais"
    Columns:
      - name: date_day
        description: "Data no formato YYYY-MM-DD"
      - name: year
        description: "Ano da data"
      - name: month
        description: "Mês da data (1-12)"
      - name: day
        description: "Dia do mês da data (1-31)"
      - name: quarter
        description: "Trimestre do ano da data (1-4)"
      - name: week_of_year
        description: "Número da semana do ano da data (1-53)"
      - name: day_of_week
        description: "Dia da semana da data (1=Segunda, 7=Domingo)"
      - name: is_weekend
        description: "Indica se a data cai em um final de semana (booleano)" 
        
  - name: dim_product
    description: "Dimensão de produtos, baseada na staging stg_production_product_details"
    tests:
      - unique:
          column_name: product_id
    Columns:
      - name: product_id
        description: "ID do produto"
      - name: product_name
        description: "Nome do produto"
      - name: is_make
        description: "Indica se o produto é fabricado internamente (booleano)"
      - name: is_finished_good
        description: "Indica se o produto é um produto acabado (booleano)"
      - name: product_color
        description: "Cor do produto"
      - name: standard_cost
        description: "Custo padrão do produto"
      - name: list_price
        description: "Preço de lista do produto"
      - name: product_line
        description: "Linha de produtos a que o produto pertence"
      - name: product_class
        description: "Classe do produto"
      - name: product_style
        description: "Estilo do produto"
      - name: product_subcategory_id
        description: "ID da subcategoria do produto"
      - name: product_model_id
        description: "ID do modelo do produto"


  - name: dim_salesperson
    description: "Dimensão de vendedores, baseada na staging stg_sales_person_details"
    tests:
      - unique:
          column_name: email_address
    Columns:
      - name: salesperson_id
        description: "ID do vendedor"
      - name: full_name
        description: "Nome completo do vendedor" 
      - name: job_title
        description: "Cargo do vendedor"
      - name: email_address
        description: "Endereço de e-mail do vendedor"
      - name: phone_number
        description: "Número de telefone do vendedor"
      - name: sales_quota
        description: "Cota de vendas do vendedor"
      - name: sales_ytd
        description: "Vendas acumuladas do ano até a data atual"
      - name: sales_last_year
        description: "Vendas do vendedor no ano passado"
      - name: territory_id
        description: "ID do território de vendas do vendedor"
      - name: territory_group
        description: "Grupo de território ao qual o vendedor pertence"
      - name: percentual_meta_batida
        description: "Percentual da meta de vendas batida pelo vendedor"
  
  - name: dim_costumer
    description: "Dimensão de clientes, baseada na staging stg_sales_customer_details"
    tests:
      - unique:
          column_name: customer_id
    Columns:
      - name: customer_id
        description: "ID do cliente"
      - name: person_id
        description: "ID da pessoa associada ao cliente"
      - name: full_name
        description: "Nome completo do cliente"
      - name: territory_name
        description: "Nome do território de vendas do cliente"
      - name: territory_group
        description: "Grupo de território ao qual o cliente pertence"
      - name: country_region_code
        description: "Código do país ou região do cliente"
      

  - name: dim_ship_method
    description: "Dimensão de métodos de envio, baseada na staging stg_shipping_method_details"
    tests:
      - unique:
          column_name: ship_method_id
    Columns:
      - name: ship_method_id
        description: "ID do método de envio"
      - name: ship_method_name
        description: "Nome do método de envio"
      - name: ship_base
        description: "Taxa base de envio"
      - name: ship_rate
        description: "Taxa de envio por unidade"
      - name: modified_date
        description: "Data da última modificação do método de envio"